### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by anthonyhendrickson** [pimentel/atom-r-exec#6]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `r-exec` package
```
Package.getStylesheetsPath (c:\Users\ahendrickson\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:460:9)
Package.getStylesheetPaths (c:\Users\ahendrickson\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:471:32)
Package.loadStylesheets (c:\Users\ahendrickson\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:453:38)
<unknown> (c:\Users\ahendrickson\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:183:19)
Package.measure (c:\Users\ahendrickson\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:163:15)
Package.load (c:\Users\ahendrickson\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:177:12)
```

**Comment by graipher** [comment]
+1

**Comment by hafen** [comment]
I have fixed all of these issues so that the package doesn't have any deprecations (see [here](https://github.com/hafen/atom-r-exec/commit/89e7dc55367b8d5319cc876437946877d0a512e3), but it is not registering with atom as an update.  This is probably something simple.  Anyone know what to to make the update show up?

**Comment by pimentel** [comment]
This seems to be fixed. Please let me know if it isn't (and please reopen the issue).
